/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlyotovaxemay;
import java.sql.Connection;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;


/**
 *
 * @author chipt
 */
public class giaodien extends javax.swing.JFrame {
    // hàm hiển thị dữ liệu
    
    /**
     * Creates new form giaodien
     */
    
    DefaultTableModel tableModel;
    
    List<xe> xeList = new ArrayList<>();
    
   
    public giaodien() {
        initComponents();
        tableModel = (DefaultTableModel) tblXe.getModel();
        
        showXe();
        
        
    }
    private void showXe(){
        xeList = chucnang.findAll();
        
        tableModel.setRowCount(0);
        
        xeList.forEach(Xe -> {
            tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, Xe.getBienSo(),
                Xe.getSoChoNgoi(),
                Xe.getLePhiTieuThuDB(),
                Xe.getLoaiXe(),
                Xe.getPhanKhoi()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbLoaiXe = new javax.swing.JComboBox<>();
        txtSoChoNgoi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPhanKhoi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtLePhiTieuThuDB = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtBienSo = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblXe = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("quanly");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhap thong tin xe"));

        jLabel2.setText("Loai Xe:");

        cbLoaiXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xe Oto", "Xe May" }));
        cbLoaiXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoaiXeActionPerformed(evt);
            }
        });

        txtSoChoNgoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoChoNgoiActionPerformed(evt);
            }
        });

        jLabel3.setText("So Cho Ngoi:");

        txtPhanKhoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhanKhoiActionPerformed(evt);
            }
        });

        jLabel4.setText("Phan Khoi:");

        jLabel5.setText("Le Phi Tieu Thu Duong Bo:");

        txtLePhiTieuThuDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLePhiTieuThuDBActionPerformed(evt);
            }
        });

        jLabel1.setText("Bien So:");

        txtBienSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBienSoActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnReset.setText("reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jButton1.setText("Đăng Xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("chart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnFind)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset)
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtBienSo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtLePhiTieuThuDB))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtPhanKhoi))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtSoChoNgoi)))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cbLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(32, 32, 32)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBienSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoChoNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhanKhoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLePhiTieuThuDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnDelete)
                    .addComponent(btnFind)
                    .addComponent(btnReset))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        tblXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Bien So", "So Cho Ngoi", "Le Phi Tieu Thu", "Loai Xe", "Phan Khoi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblXe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBienSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBienSoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBienSoActionPerformed

    private void cbLoaiXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoaiXeActionPerformed
        // TODO add your handling code here:
        if(cbLoaiXe.getSelectedIndex() == 1){
            txtLePhiTieuThuDB.setEnabled(false);
            txtSoChoNgoi.setEnabled(false);
        }
        if(cbLoaiXe.getSelectedIndex() == 0){
            txtLePhiTieuThuDB.setEnabled(true);
            txtSoChoNgoi.setEnabled(true);
        }
    }//GEN-LAST:event_cbLoaiXeActionPerformed

    private void txtSoChoNgoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoChoNgoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoChoNgoiActionPerformed

    private void txtPhanKhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhanKhoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhanKhoiActionPerformed

    private void txtLePhiTieuThuDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLePhiTieuThuDBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLePhiTieuThuDBActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(cbLoaiXe.getSelectedIndex() == 0){
        String bien_So = txtBienSo.getText();
        String Phan_Khoi = txtPhanKhoi.getText();
        int lephitieuthu_DB = Integer.parseInt(txtLePhiTieuThuDB.getText());
        int so_cho_ngoi = Integer.parseInt(txtSoChoNgoi.getText());
        String Loai_Xe = cbLoaiXe.getSelectedItem().toString();
        
        xe std = new xe(bien_So, Phan_Khoi, Loai_Xe, lephitieuthu_DB, so_cho_ngoi);
        
        chucnang.insert(std);
        
        showXe();
        }
        else{

        String bien_So = txtBienSo.getText();
        String Phan_Khoi = txtPhanKhoi.getText();
        int lephitieuthu_DB = 0;
        int so_cho_ngoi = 0;
        String Loai_Xe = cbLoaiXe.getSelectedItem().toString();
        
        xe std = new xe(bien_So, Phan_Khoi, Loai_Xe, lephitieuthu_DB, so_cho_ngoi);
        
        chucnang.insert(std);
        
        showXe();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Enter Bien So Xe");
        if(input != null && input.length() > 0){
            xeList = chucnang.findByBienSo(input);
            
            tableModel.setRowCount(0);
        
        xeList.forEach(Xe -> {
            tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, Xe.getBienSo(),
                Xe.getPhanKhoi(),
                Xe.getLoaiXe(),
                Xe.getLePhiTieuThuDB(),
                Xe.getSoChoNgoi()});
        });
        }
        else{
            showXe();
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtBienSo.setText("");
        txtPhanKhoi.setText("");
        txtLePhiTieuThuDB.setText("");
        txtSoChoNgoi.setText("");
        cbLoaiXe.setSelectedIndex(0);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblXe.getSelectedRow();
        if (selectedIndex >= 0){
            xe std = xeList.get(selectedIndex);
            
            int option = JOptionPane.showConfirmDialog(this, "Do you want to delete this item?");
            System.out.println("option: " + option);
            
            if(option == 0){
                chucnang.delete(std.getId());
                
                showXe();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dangnhap l = new dangnhap();
        l.setVisible(true); //hiển thị màn hình form đăng nhập
        this.dispose();// thoát khỏi cửa sổ form đăng ký khi đã nhấn vào đăng nhập
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          int chart1 = 0;
          Connection connection = null;
          Statement statement = null;
          
          
          
          try {
            connection = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/xe1", "root", "");
            
            
            String sql = "select COUNT(lephitieuthu_DB) AS count FROM xe WHERE lephitieuthu_DB > 0";
            
            statement = connection.createStatement();
            
            ResultSet resultSet1 = statement.executeQuery(sql);
            
              if (resultSet1.next()) {
                  chart1 = resultSet1.getInt("count");
              }
              resultSet1.close();
        } catch (Exception ex) {
            Logger.getLogger(chucnang.class.getName()).log(Level.SEVERE, null, ex);
        }  finally {
            if(statement != null){
                try {
                    statement.close();
                } catch (SQLException ex) {
                    Logger.getLogger(chucnang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (connection != null) {
                try {
                    connection.close();
                } catch (SQLException ex) {
                    Logger.getLogger(chucnang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
          
          
          
         int chart2 = 0;
        Connection connection2 = null;
        Statement statement2 = null;
         
         try {
            connection2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/xe1", "root", "");
            
            
            String sql2 = "select COUNT(lephitieuthu_DB) AS count1 FROM xe WHERE lephitieuthu_DB = 0";
            
            statement2 = connection2.createStatement();
            
            ResultSet resultSet2 = statement2.executeQuery(sql2);
            
              if (resultSet2.next()) {
                  chart2 = resultSet2.getInt("count1");
              }
              resultSet2.close();
        } catch (Exception ex) {
            Logger.getLogger(chucnang.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if(statement2 != null){
                try {
                    statement2.close();
                } catch (SQLException ex) {
                    Logger.getLogger(chucnang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (connection2 != null) {
                try {
                    connection2.close();
                } catch (SQLException ex) {
                    Logger.getLogger(chucnang.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            
        }
         

         
         DefaultPieDataset pieDataset = new DefaultPieDataset();
         pieDataset.setValue("xe O to", Integer.valueOf(chart1));
         pieDataset.setValue("xe may", Integer.valueOf(chart2));
        JFreeChart chart= ChartFactory.createPieChart("xe chart", pieDataset, true, true, true);
        
        PiePlot P=(PiePlot)chart.getPlot();
        
        ChartFrame frame =new ChartFrame ("Pie Chart", chart);
        frame.setVisible (true);
        frame.setSize (450,500);

//plan: tạo 1 câu truy vấn bảng lệ phí tiêu thụ đường bộ của ô tô và xe máy
// gợi ý: hàm count
// lưu kết quả vào 1 biến rồi đem vô tạo chart



    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new giaodien().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbLoaiXe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblXe;
    private javax.swing.JTextField txtBienSo;
    private javax.swing.JTextField txtLePhiTieuThuDB;
    private javax.swing.JTextField txtPhanKhoi;
    private javax.swing.JTextField txtSoChoNgoi;
    // End of variables declaration//GEN-END:variables
}
